- action:
  - alias: Bec
    data:
      entity_id: switch.bec
    service: switch.turn_on
  alias: Turn on bec living
  condition:
  - above: '0'
    below: '17'
    condition: numeric_state
    entity_id: sensor.sn1_ldr
  id: '1504522812033'
  trigger:
  - entity_id: sensor.sn1_pir
    from: 'off'
    platform: state
    to: 'on'
- action:
  - alias: Bec
    data:
      entity_id: switch.bec
    service: switch.turn_off
  alias: Turn off bec living
  condition: []
  id: '1504808952838'
  trigger:
  - entity_id: sensor.sn1_pir
    from: 'on'
    platform: state
    to: 'off'
    for:
      seconds: 20

#Notify if wather pomp is on by itself
-  alias: Notify Dani when wather pump is opened
   trigger:
     - platform: state
       entity_id: switch.mqtt_switch_1
       from: 'off'
       to: 'on'
     - platform: state
       entity_id: switch.mqtt_switch_2
       from: 'off'
       to: 'on'
   action:
     - service: notify.ios_dani
       data:
         message: Wather pump ON 
#         data:
#           push:
#             sound: "US-EN-Daisy-Water-Heater-Leak.wav"

-  alias: Notify Dani when wather pump is opened
   trigger:
     - platform: state
       entity_id: switch.mqtt_switch_1
       from: 'on'
       to: 'off'
   action:
     - service: notify.ios_dani
       data:
         message: Wather pump OFF

-  alias: Notify Dani when air quality is bad
   trigger:
     - platform: numeric_state
       entity_id: sensor.sn1_ldr
       above: 80
       below: 500
   action:
     - service: notify.ios_dani
       data_template:
         title: "Air-quiality"
         message: "Bad air-quality --> {{ states.sensor.sn1_ldr.state }} <--"

#Autoamtion for backup HA. Start at 1 minute after midnight 
- alias: 'backup automation'
  trigger:
    platform: time
    hours: 0
    minutes: 1
    seconds: 0
  action:
    service: shell_command.backupha

- alias: "Garden irrigation"
  trigger:
    platform: numeric_state
    entity_id: sensor.soil_moister
    above: 5
    below: 23
  action:
    service: switch.turn_on
    entity_id: switch.mqtt_switch_1

- alias: "Garden irrigation off"
  trigger:
    platform: state
    entity_id: switch.mqtt_switch_1
    to: 'on'      
    for:
      minutes: 10
  action:
    - service: switch.turn_off
      entity_id: switch.mqtt_switch_1
