- platform: mqtt
  name: "Soil Moister"
  state_topic: "/house/soil1/"
  unit_of_measurement: "%"
  qos: 0

- platform: mqtt
  state_topic: "bruh/sensornode1"
  name: "SN1 Solar"
  unit_of_measurement: '째C'
  value_template: '{{ value_json.solartemp | round(1) }}'
  icon: mdi:thermometer-lines

- platform: mqtt
  state_topic: "bruh/sensornode1"
  name: "SN1 Humidity"
  unit_of_measurement: "%"
  value_template: '{{ value_json.humidity | round(1) }}'

- platform: mqtt
  state_topic: "bruh/sensornode1"
  name: "SN1 LDR"
  ##This sensor is not calibrated to actual LUX. Rather, this a map of the input voltage ranging from 0 - 1023.
  unit_of_measurement: "LUX"
  value_template: '{{ value_json.ldr }}'

- platform: mqtt
  state_topic: "bruh/sensornode11"
  name: "ThermalSensor"
  value_template: '{{ value_json.AMGthermal }}'

- platform: mqtt
  state_topic: "bruh/sensornode1"
  name: "SN1 PIR"
  value_template: '{{ value_json.motion }}'

- platform: mqtt
  state_topic: "bruh/sensornode1"
  name: "SN1 Temperature"
  unit_of_measurement: '째C'
  value_template: '{{ ((value_json.temperature | int - 32) * 5 / 9) | round(1) }}'

- platform: mqtt
  state_topic: "bruh/sensornode12"
  name: "SN1 Temperature23"
  unit_of_measurement: '째C'
  value_template: '{{ value_json.temp23 | round(1) }}'

- platform: mqtt
  state_topic: "bruh/sensornode1"
  name: "SN1 Real Feel"
  unit_of_measurement: '째C'
  value_template: '{{ value_json.heatIndex | round(1) }}'

- platform: bh1750
  name: Ambient light
  operation_mode: one_time_high_res_mode_1
  measurement_delay_ms: 200
  scan_interval: 1

- platform: systemmonitor
  resources:
    - type: disk_use_percent
      arg: /
    - type: memory_free
    - type: processor_use
    - type: since_last_boot

#- platform: filesize
#  name: DB size
#  file_paths:
#    - /var/lib/mysql/ibdata1 

- platform: uptime
  name: uptime
  unit_of_measurement: hours

